#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, timezone
import argparse
import json
import re

ROOT = Path(__file__).resolve().parents[1]


def read(path):
    return Path(path).read_text(encoding='utf-8') if path else ''


def first_match(pattern, text, fallback='unknown'):
    m = re.search(pattern, text)
    return m.group(1) if m else fallback


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--validation-log', required=True)
    parser.add_argument('--application-log', required=True)
    args = parser.parse_args()

    app = (ROOT / 'app.js').read_text(encoding='utf-8')
    app_version = first_match(r"const APP_VERSION = '([^']+)';", app)
    validation = read(args.validation_log).strip()
    application = read(args.application_log).strip()
    validation_summary = first_match(r'Validation:\s*(\d+/\d+ checks passed)', validation)
    application_summary = first_match(r'Application regression:\s*(\d+/\d+ passed)', application)

    packs = {}
    for name in ('data-pack.json', 'rules-pack.json', 'certificate-rules.json'):
        obj = json.loads((ROOT / name).read_text(encoding='utf-8'))
        packs[name] = {
            'schemaVersion': obj.get('schemaVersion'),
            'packVersion': obj.get('packVersion'),
            'appVersion': obj.get('appVersion'),
            'snapshot': obj.get('snapshot'),
            'updatedAt': obj.get('updatedAt'),
            'metadataUpdatedAt': obj.get('metadataUpdatedAt'),
        }

    generated = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')
    lines = [
        '# Regression Test Report',
        '',
        f'- App version: **{app_version}**',
        f'- Generated: **{generated}**',
        f'- Data/markup validation: **{validation_summary}**',
        f'- Application regression: **{application_summary}**',
        '- JavaScript syntax (`node --check app.js`): **PASS**',
        '',
        '## Data pack metadata',
        '',
        '| File | Schema | Pack version | App version | Snapshot | Source data updated | Metadata updated |',
        '| --- | ---: | --- | --- | --- | --- | --- |',
    ]
    for name, meta in packs.items():
        lines.append('| {name} | {schemaVersion} | {packVersion} | {appVersion} | {snapshot} | {updatedAt} | {metadataUpdatedAt} |'.format(name=name, **meta))

    lines += [
        '',
        '## Data / markup validation',
        '',
        '```text',
        validation,
        '```',
        '',
        '## Application regression',
        '',
        '```text',
        application,
        '```',
        '',
        '> This file is generated by GitHub Actions. Do not maintain pass counts manually.',
        '',
    ]
    (ROOT / 'REGRESSION_TEST_REPORT.md').write_text('\n'.join(lines), encoding='utf-8')
    print(f'Generated REGRESSION_TEST_REPORT.md for app {app_version}')


if __name__ == '__main__':
    main()
